/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lanczeniebazy;

import com.github.lgooddatepicker.optionalusertools.TimeChangeListener;
import com.sun.corba.se.impl.orbutil.ORBConstants;
import com.sun.org.apache.bcel.internal.generic.AALOAD;
import com.sun.xml.internal.ws.streaming.XMLStreamReaderUtil;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

public class Dodawanie extends javax.swing.JFrame {

Connection conn = null;
PreparedStatement pst = null;
ResultSet rs = null;
private final String url="jdbc:postgresql://localhost:5432/postgres";
private final String nazwa = "postgres";
private final String haslo = "postgres";
private ArrayList lista_id_p = new ArrayList();
private ArrayList lista_id_l = new ArrayList();
private ArrayList lista_id_p_1 = new ArrayList();
private ArrayList lista_id_l_1= new ArrayList();
private boolean use = false;


    public Dodawanie() {
                
        initComponents();
        try{
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection(url, nazwa, haslo);
            java.sql.Statement st = conn.createStatement();
            String Sql = "Select * from lekarze";
            rs = st.executeQuery(Sql);
            while(rs.next()){
                ComboBoxDoktor.addItem(rs.getString("imie")+" "+rs.getString("nazwisko")+" "+rs.getString("specjalizacja"));
                ComboBoxDoktor1.addItem(rs.getString("imie")+" "+rs.getString("nazwisko")+" "+rs.getString("specjalizacja"));
                lista_id_l.add(rs.getInt("id"));
                lista_id_l_1.add(rs.getInt("id"));
            }
            Sql = "Select * from placowki";
            rs = st.executeQuery(Sql);
            while(rs.next()){
                ComboBoxPlacowka.addItem(rs.getString("Nazwa"));
                ComboBoxPlacowka1.addItem(rs.getString("Nazwa"));
                lista_id_p.add(rs.getInt("id"));
                lista_id_p_1.add(rs.getInt("id"));
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(this,"Err "+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Okno_Listy = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnback = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        btnShowList = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        btnChangeValues = new javax.swing.JButton();
        TxtName1 = new javax.swing.JTextField();
        txtPesel1 = new javax.swing.JTextField();
        TxtSurname1 = new javax.swing.JTextField();
        TxtMiasto1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ComboBoxDoktor1 = new javax.swing.JComboBox<>();
        ComboBoxPlacowka1 = new javax.swing.JComboBox<>();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        timePicker2 = new com.github.lgooddatepicker.components.TimePicker();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnList = new javax.swing.JButton();
        TxtName = new javax.swing.JTextField();
        txtPesel = new javax.swing.JTextField();
        TxtSurname = new javax.swing.JTextField();
        TxtMiasto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ComboBoxDoktor = new javax.swing.JComboBox<>();
        ComboBoxPlacowka = new javax.swing.JComboBox<>();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        timePicker1 = new com.github.lgooddatepicker.components.TimePicker();

        jScrollPane2.setFocusable(false);
        jScrollPane2.setVerifyInputWhenFocusTarget(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        btnback.setText("Powrót");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnChange.setText("Zmień");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        btnShowList.setText("Wyswietl liste");
        btnShowList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowListActionPerformed(evt);
            }
        });

        btnDelete.setText("Usun");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Okno_ListyLayout = new javax.swing.GroupLayout(Okno_Listy.getContentPane());
        Okno_Listy.getContentPane().setLayout(Okno_ListyLayout);
        Okno_ListyLayout.setHorizontalGroup(
            Okno_ListyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Okno_ListyLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(Okno_ListyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Okno_ListyLayout.createSequentialGroup()
                        .addComponent(btnback)
                        .addGap(339, 339, 339)
                        .addComponent(btnShowList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChange)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        Okno_ListyLayout.setVerticalGroup(
            Okno_ListyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Okno_ListyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Okno_ListyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShowList)
                    .addComponent(btnChange)
                    .addComponent(btnback)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        btnChangeValues.setText("Zmien");
        btnChangeValues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeValuesActionPerformed(evt);
            }
        });

        txtPesel1.setToolTipText("Pesel");

        jLabel8.setText("Imie");

        jLabel9.setText("Nazwisko");

        jLabel10.setText("Pesel");

        jLabel11.setText("Lekarz");

        jLabel12.setText("Dzień");

        jLabel13.setText("Miasto");

        jLabel14.setText("Placówka");

        ComboBoxDoktor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz Lekarza" }));
        ComboBoxDoktor1.setToolTipText("Wybierz Lekarza");

        ComboBoxPlacowka1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz Placówke" }));
        ComboBoxPlacowka1.setToolTipText("Wybierz Placowke");
        ComboBoxPlacowka1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxPlacowka1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtName1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtSurname1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPesel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxDoktor1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChangeValues, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtMiasto1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxPlacowka1, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE))
                        .addGap(86, 86, 86))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(timePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPesel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtSurname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TxtMiasto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(ComboBoxPlacowka1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxDoktor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(timePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnChangeValues)
                .addGap(42, 42, 42))
        );

        ComboBoxDoktor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz Lekarza" }));

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdd.setText("Dodaj");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnList.setText("Lista");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        txtPesel.setToolTipText("Pesel");

        jLabel1.setText("Imie");

        jLabel2.setText("Nazwisko");

        jLabel3.setText("Pesel");

        jLabel4.setText("Lekarz");

        jLabel5.setText("Dzień");

        jLabel6.setText("Miasto");

        jLabel7.setText("Placówka");

        ComboBoxDoktor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz Lekarza" }));
        ComboBoxDoktor.setToolTipText("Wybierz Lekarza");

        ComboBoxPlacowka.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz Placówke" }));
        ComboBoxPlacowka.setToolTipText("Wybierz Placowke");
        ComboBoxPlacowka.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxPlacowkaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtSurname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPesel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxDoktor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtMiasto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxPlacowka, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(86, 86, 86))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(timePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(42, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtMiasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(ComboBoxPlacowka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxDoktor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(timePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnList)
                .addGap(13, 13, 13))
        );

        ComboBoxDoktor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz Lekarza" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        boolean spr_peselu=false;
        Timestamp ts = new Timestamp(
                jXDatePicker1.getDate().getYear(),
                jXDatePicker1.getDate().getMonth(),
                jXDatePicker1.getDate().getDate(),
                timePicker1.getTime().getHour(),
                timePicker1.getTime().getMinute(),
                timePicker1.getTime().getSecond(), 
                timePicker1.getTime().getNano()
        );
        
        do
        {   String spr=txtPesel.getText();
            if( spr.length() != 11)
            {JOptionPane.showMessageDialog(this,"Pesel nie składa sie z 11 cyfr");}
            else
            {
                try {
                    Class.forName("org.postgresql.Driver");
                    conn = DriverManager.getConnection(url, nazwa, haslo);
                    String Sql="select dodaj_wizyte_f(?,?,?,?,?,?)";
                    pst = conn.prepareStatement(Sql);
                    
                    pst.setLong(1,Long.valueOf(txtPesel.getText()));
                    pst.setString(2,TxtName.getText());
                    pst.setString(3,TxtSurname.getText());
                    pst.setString(4,TxtMiasto.getText());
                    pst.setTimestamp(5, ts);
                    pst.setLong(6,Long.valueOf(lista_id_l.get(ComboBoxDoktor.getSelectedIndex()-1).toString()));
                    pst.executeQuery();
                    JOptionPane.showMessageDialog(this, "Dodano");
        
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,e.getMessage());
                    }
                spr_peselu = true;
            }
        }while(spr_peselu = false);
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        // TODO add your handling code here:
        Okno_Listy.setSize(Okno_Listy.getPreferredSize().width,Okno_Listy.getPreferredSize().height);
        Okno_Listy.setVisible(true);
        
        
        
    }//GEN-LAST:event_btnListActionPerformed

    private void ComboBoxPlacowkaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxPlacowkaItemStateChanged
        try{
        Class.forName("org.postgresql.Driver");
        conn = DriverManager.getConnection(url, nazwa, haslo);
        String Sql = "Select * from lekarze_f('"+ComboBoxPlacowka.getSelectedItem().toString()+"')";
        java.sql.Statement st = conn.createStatement();        
        rs = st.executeQuery(Sql);
        ComboBoxDoktor.removeAllItems();
        ComboBoxDoktor.addItem("Wybierz doktora");
        lista_id_l.clear();
        
        while(rs.next()){
             ComboBoxDoktor.addItem(rs.getString("imie")+" "+rs.getString("nazwisko")+" "+rs.getString("specjalizacja"));
             lista_id_l.add(rs.getInt("id"));
         }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
    }//GEN-LAST:event_ComboBoxPlacowkaItemStateChanged

    private void btnShowListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowListActionPerformed
        Object[] columns = {"data wizyty","Pesel","Imie Osoby","Nazwisko Osoby","Imie Lekarza", "Nazwisko","Nazwa Placowki","Miasto"};
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);
        jTable1.setModel(model);
        Object[] row = new Object[8];
        try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection(url, nazwa, haslo);
            String Sql = "Select * from list2()";
            java.sql.Statement st = conn.createStatement();

            rs = st.executeQuery(Sql);
            while(rs.next()){
                row[0] = rs.getString("data_wizyty");
                row[1] = rs.getString("pesel");
                row[2] = rs.getString("imie_o");
                row[3] = rs.getString("nazwisko_o");
                row[4] = rs.getString("imie_l");
                row[5] = rs.getString("nazwisko_l");
                row[6] = rs.getString("nazwa_placowki");
                row[7] = rs.getString("miasto_l");

                model.addRow(row);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(Okno_Listy, ex.getMessage());
        }
    }//GEN-LAST:event_btnShowListActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        Okno_Listy.setVisible(false);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        jFrame1.setSize(jFrame1.getPreferredSize().width,jFrame1.getPreferredSize().height);
        jFrame1.setVisible(true);
        
        txtPesel1.setText(jTable1.getValueAt(jTable1.getSelectedRow(),1).toString());
        TxtName1.setText(jTable1.getValueAt(jTable1.getSelectedRow(),2).toString());
        TxtSurname1.setText(jTable1.getValueAt(jTable1.getSelectedRow(),3).toString());
        TxtMiasto1.setText(jTable1.getValueAt(jTable1.getSelectedRow(),7).toString());
        
                
        
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
                    Class.forName("org.postgresql.Driver");
                    conn = DriverManager.getConnection(url, nazwa, haslo);
                    String Sql="select usun(?)";
                    pst = conn.prepareStatement(Sql);                   
                    pst.setLong(1,Long.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(),1).toString()));
                    pst.executeQuery();
                    JOptionPane.showMessageDialog(this, "Usunięto");
        
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(Okno_Listy,e.getMessage());
                    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnChangeValuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeValuesActionPerformed
        Timestamp ts = new Timestamp(
                jXDatePicker2.getDate().getYear(),
                jXDatePicker2.getDate().getMonth(),
                jXDatePicker2.getDate().getDate(),
                timePicker2.getTime().getHour(),
                timePicker2.getTime().getMinute(),
                timePicker2.getTime().getSecond(), 
                timePicker2.getTime().getNano()
        );
        
        try {
                    Class.forName("org.postgresql.Driver");
                    conn = DriverManager.getConnection(url, nazwa, haslo);
                    String Sql="select update(?,?,?,?,?,?)";
                    pst = conn.prepareStatement(Sql);
                    
                    pst.setLong(1,Long.valueOf(txtPesel1.getText()));
                    pst.setString(2,TxtName1.getText());
                    pst.setString(3,TxtSurname1.getText());
                    pst.setString(4,TxtMiasto1.getText());
                    pst.setTimestamp(5, ts);
                    pst.setLong(6,Long.valueOf(lista_id_l_1.get(ComboBoxDoktor1.getSelectedIndex()-1).toString()));
                    pst.executeQuery();
                    JOptionPane.showMessageDialog(this, "Zmieniono");
        
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,e.getMessage());
                    }
        
       
    }//GEN-LAST:event_btnChangeValuesActionPerformed

    private void ComboBoxPlacowka1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxPlacowka1ItemStateChanged
        try{
        Class.forName("org.postgresql.Driver");
        conn = DriverManager.getConnection(url, nazwa, haslo);
        String Sql = "Select * from lekarze_f('"+ComboBoxPlacowka1.getSelectedItem().toString()+"')";
        java.sql.Statement st = conn.createStatement();        
        rs = st.executeQuery(Sql);
        ComboBoxDoktor1.removeAllItems();
        ComboBoxDoktor1.addItem("Wybierz doktora");
        lista_id_l_1.clear();
        while(rs.next()){
             ComboBoxDoktor1.addItem(rs.getString("imie")+" "+rs.getString("nazwisko")+" "+rs.getString("specjalizacja"));
             lista_id_l_1.add(rs.getInt("id"));
         }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
    }//GEN-LAST:event_ComboBoxPlacowka1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dodawanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dodawanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dodawanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dodawanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dodawanie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxDoktor;
    private javax.swing.JComboBox<String> ComboBoxDoktor1;
    private javax.swing.JComboBox<String> ComboBoxPlacowka;
    private javax.swing.JComboBox<String> ComboBoxPlacowka1;
    private javax.swing.JFrame Okno_Listy;
    private javax.swing.JTextField TxtMiasto;
    private javax.swing.JTextField TxtMiasto1;
    private javax.swing.JTextField TxtName;
    private javax.swing.JTextField TxtName1;
    private javax.swing.JTextField TxtSurname;
    private javax.swing.JTextField TxtSurname1;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnChangeValues;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnShowList;
    private javax.swing.JButton btnback;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private com.github.lgooddatepicker.components.TimePicker timePicker1;
    private com.github.lgooddatepicker.components.TimePicker timePicker2;
    private javax.swing.JTextField txtPesel;
    private javax.swing.JTextField txtPesel1;
    // End of variables declaration//GEN-END:variables
}
